# NAME: Harrison Cassar
# EMAIL: Harrison.Cassar@gmail.com
# ID: 505114980

# build the distribution tarball
dist:
	tar -zvcf lab4a-505114980.tar.gz Makefile README my_beaglebone.jpg connected.png copy.png build_run.png git.png

# delete all files created by the Makefile, and return the directory to its freshly untared state
clean:
	rm -f *~ *.tar.gz

.PHONY: clean dist
